trois_wa_blog:
    resource: "@TroisWABlogBundle/Resources/config/routing.yml"
    prefix:   /




trois_wa_my_first_project_website:
    resource: "@TroisWAMyFirstProjectWebsiteBundle/Resources/config/routing.yml"
    prefix:   /

